### ISSUE TITLE
All old Chloe patches for review

### ISSUE THREAD

**Issue by agb1** [RoxanneSHS/ChloeEET#2]
https://github.com/BiGWorldProject/BiG-World-Fixpack/tree/master/BiG%20World%20Fixpack/Chloe

:: Chloe - Chloe NPC v1.5

:: Beleg33's spell casting swords fix
:: http://www.shsforums.net/topic/42220-fixes-for-the-big-fixpack/?p=543398

:: Taimon's preset targetting SPL fix
:: http://www.shsforums.net/topic/42220-fixes-for-the-big-fixpack/?p=546783

:: cmorgan's fix for suicidal weapons
:: http://www.shsforums.net/topic/45516-chloes-weapons-killiing-their-owner/?p=492084

:: Lollorian's string tag fixes
:: http://www.shsforums.net/topic/42220-fixes-for-the-big-fixpack/?p=500837

:: cmorgan's ToBEx compatible ADD_KIT fix
:: http://forums.gibberlings3.net/index.php?showtopic=21964&view=findpost&p=183270

:: Roxanne's Imoen no script assignment
:: http://www.shsforums.net/topic/58186-anybody-take-on-the-chloe-mod/?p=581732

:: Spurious reference to non-existent oggdec removed
:: - LINK NOT FOUND -

**Comment by RoxanneSHS** [comment]
All the weapon related issues are no longer relevant, I reworked her weapons (only useable by Chloe) with the new features from EE including those references above where still applicable.

I missed Lollorian's string tag fixes, I found a number of them myself but will do another check today.

At this moment I suggest not to apply any of the fixpack actions to the EE/EET Chloe -I will incorporate the missing stringfixes if still necessary.
