### ISSUE TITLE
Protection from Spell effects in cre files

### ISSUE THREAD

**Issue by agb1** [RoxanneSHS/ChloeEET#3]
Nightfarer just reported this issue in the original mod.

The 5 creatures of the mod (chloe13.cre, chloe15.cre, chloe7.cre, chloe9.cre, ChloeNut.cre) have wrong resources assigned to Protection From Spell effects.   All the effects of the creatures that come with the mod point to the right spells... but with a space added at the end resulting in non-existing resources.

As an example:
Protection From Spell (206):
Resource: SPCL641 .SPL (space before the .)

Reporting here in case you did not correct this issue already in your version.

**Comment by RoxanneSHS** [comment]
Thank you - I made the changes where still needed for EE.
